### ISSUE TITLE
Spelling error "deliminer"

### ISSUE THREAD

**Issue by DirkHaar** [notepad-plus-plus/userDefinedLanguages#147]
In https://github.com/notepad-plus-plus/userDefinedLanguages/blob/master/UDLs/SAS_byCathLawrence.xml
there are three occurences of "deliminer" (followed by 1,2,3) instead of "delimiter".
Please change it.

**Comment by pryrt** [comment]
It's not a spelling error (or, rather, it's an intentional spelling error).  In this repository, there are two "eras" of UDL included.  The first "era" was from ancient copies of Notepad++, and used the spelling DELMINER# for that attribute value.  The second "era" was from modern Notepad++, which uses UDL 2.1 syntax for the UDL files.  You can tell which "era" a UDL file is from by looking at the `<UserLang ...` line: 
* OLD: `<UserLang name="SAS" ext="sas SAS">` (from [SAS_byCathLawrence](../blob/master/UDLs/SAS_byCathLawrence.xml))
* NEW: `<UserLang name="ABAP2" ext="abap" udlVersion="2.1">` (from [ABAP_by_MithunKumar](../blob/master/UDLs/ABAP_by_MithunKumar.xml))

Modern Notepad++ can understand both files... but if you load an "old era" UDL file, and then make changes (change a color or whatever), it will be saved as a `udlVersion="2.1"` file from then on.

Just changing the spelling won't "fix" the older-style UDL (and might make it so Notepad++ doesn't understand it, because that was the expected spelling of that attribute value).

However, when I get around to fixing #148, the "spelling" will be fixed for free.  (The idea for #148 has been in the back of my mind for months, but I had never put in the issue for tracking purposes, so I never remembered to do it; your post reminded me.)

**Comment by pryrt** [comment]
closed, because superseded by #148: when #148 is implemented, this will automatically be fixed

**Comment by pryrt** [comment]
#148 was closed by #149 , so the "spelling error" is gone
