### ISSUE TITLE
Now User Defined Language Directory

### ISSUE THREAD

**Issue by gnosisgithub** [notepad-plus-plus/userDefinedLanguages#267]
I reinstalled Notepad++ several times and a User Defined directory never seems to be installed. I created it in the top level naming it 'User Defined Language' quit and relaunched and it still does not see the directory:
"Language > User Defined Language > Open User Defined Language folder..." 

Nor does Notepad++ register the two user defined xml files I placed in that directory. 

Suggestions on how to proceed?

**Comment by pryrt** [comment]
This repository is for sharing of UDL definitions that people have.  It is not the help-wanted for how to use Notepad++, even the UDL portion of Notepad++.  I will try to do a brief reply here to help you, but if this isn't sufficient for you, you will need to go to the "Help Wanted" section of the Notepad++ Community Forum -- https://community.notepad-plus-plus.org/category/4/help-wanted

\----

> I created it in the top level naming it 'User Defined Language'

I cannot tell whether you mean you named the language "User Defined Language" or if you named the directory "User Defined Language" -- but either action will be ineffective.

The name of the directory is `%AppData%\Notepad++\userDefineLangs\` [🛈](https://community.notepad-plus-plus.org/topic/15740/faq-desk-what-is-appdata "FAQ: What is %AppData%?") -- but, as the User Manual [explains](https://npp-user-manual.org/docs/user-defined-language-system/#udl-file-locations), when you use the GUI to create the UDL definition, it saves it in the default `%AppData%\Notepad++\userDefineLang.xml` file, rather than in a separate file in the subdirectory I mentioned.  The Manual also has a [section called "Keeping UDL Files Separate"](https://npp-user-manual.org/docs/user-defined-language-system/#keeping-udl-files-separate) which explains how to go about saving the UDL in such a manner that it goes in the `...\userDefineLangs\` directory instead of in `...\userDefineLang.xml`

On the other hand, if you meant that you named the _language_ "User Defined Language", Notepad++ will not actually save a language with that name.  You need to give it a different name when you save it -- the dummy name that you get before doing a **Save as...** is a "temporary name", and Notepad++ does not save any changes you make to that dummy name.
![image](https://github.com/notepad-plus-plus/userDefinedLanguages/assets/17455758/e73aefb7-b93d-4a3f-ba7c-2d21be6cad7e)

Again, if this isn't sufficient for you, please ask in the Community, because question-and-answer is not the purpose of the User Defined Language Collection.
