### ISSUE TITLE
udl for JSON - modify to add comment highlighting

### ISSUE THREAD

**Issue by helarsen** [notepad-plus-plus/userDefinedLanguages#58]
In NP++ there is color high lighting for JSON. I want to **customize** it so it can **highlight comments** also. The file is standard JSON apart from the fact that what follows // are considered comments. Here is a simple example

>{
  "cam_left": 85786, // _this should become a highlighted text_ 
  "cam_right": 53112 //  _this should become a highlighted text_ 
// _..as well as this_.
}

I though it would be the simplest to start from the standard JSON and modify that, but I cant find this in the list: [https://github.com/notepad-plus-plus/userDefinedLanguages/blob/master/udl-list.md](url)
found here: https://github.com/notepad-plus-plus/userDefinedLanguages#using-a-udl-from-this-collection
can someone guide me?

**Comment by helarsen** [comment]
I discovered that setting the file to use java high-lighting it works actually very good.
Except that it has to be set each time a JSON file loads.

**Comment by pryrt** [comment]
Technically, [JSON doesn't allow comments](https://stackoverflow.com/questions/244777/can-comments-be-used-in-json); but many people use JavaScript-style comments inside JSON, so much so that it's become _de facto_ allowed.

> I though it would be the simplest to start from the standard JSON and modify that

The builtin lexers are completely separate beasts from the User Defined Languages, and are coded individually in C++ by the Scintilla team, then included as part of Notepad++; the UDL is a single lexer that uses very simple parsing to match certain strings for highlighting.  You cannot just modify a builtin lexer into a UDL.

> setting the file to use java high-lighting it works actually very good.

I would've suggested "JavaScript" highlighting instead, because Java is a completely separate beast from JavaScript; and JavaScript was the basis for the data-exchange-format called JSON ("JavaScript Object Notation", if I remember correctly).

But back to your main point:

The JSON builtin lexer technically _does_ support comment highlighting: the Notepad++ wrapper around that lexer just doesn't expose that option, and it defaults to off.

As described [here](https://community.notepad-plus-plus.org/user/peterjones), if you use PythonScript, you can use `editor.setProperty("lexer.json.allow.comments",1)` in your `startup.py` to always enable JSON comments, those comments will properly highlight.

Or, if you prefer NppExec plugin to the PythonScript plugin, Michael Vincent supplied a [NppExec script here](https://community.notepad-plus-plus.org/post/54489) that accomplishes the same thing.

If you wanted to go to [the Notepad++ issues page](/notepad-plus-plus/notepad-plus-plus/issues) and request an option in preferences to enable/disable JSON comment highlighting, I would upvote it (but I don't have any power to decide whether or not to implement that feature) -- if you do, come back here and reply with a link to that issue.  If you do submit that issue, I would recommend suggesting that the option go on the Languages tab, next to "Treat backslash as escape character for SQL".

Good luck, and happy Notepad++ing

**Comment by megapro17** [comment]
> As described [here](https://community.notepad-plus-plus.org/user/peterjones), if you use PythonScript, you can use `editor.setProperty("lexer.json.allow.comments",1)` in your `startup.py` to always enable JSON comments, those comments will properly highlight.

Is there any easier way without additional plugins?

**Comment by pryrt** [comment]
> Is there any easier way without additional plugins?

No.  

As I said in February, 
> If you wanted to go to the [Notepad++ issues page](https://github.com/notepad-plus-plus/notepad-plus-plus/issues) and request an option in preferences to enable/disable JSON comment highlighting, I would upvote it (but I don't have any power to decide whether or not to implement that feature) -- if you do, come back here and reply with a link to that issue. If you do submit that issue, I would recommend suggesting that the option go on the Languages tab, next to "Treat backslash as escape character for SQL".

The feature will never be added to Notepad++ if no one makes a request in the right spot.  This closed issue is not the right spot, as the Notepad++ application developers aren't looking for Notepad++ feature requests in the repo which is used only to store user-submitted UDL files.

**Comment by tilleul** [comment]
Request has been made in NPP main repo, upvote if you feel like it :)

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11713
